row = 8
col = 8
black = 0
white = 1
board_box_width = 50
board_box_height = 50
chess_radius = 22
prompt_radius = 10
prompt_color = "green"
board_left_up_x = 50
board_left_up_y = 50
board_right_down_x = board_left_up_x + board_box_width * row
board_right_down_y = board_left_up_y + board_box_height * col
left_up_chess_x = board_left_up_x + board_box_width / 2
left_up_chess_y = board_left_up_y + board_box_height / 2
line_color = "#111"
board_bg_color = "#e3d94a"
board_outline_color = "#111"
screen_width = 500
screen_height = 600
time_limit = 60
single_time_limit = 3
